UPDATE TB_USUARIO set SITUACAO = 'I' where DS_EMAIL = 'bruno.loeser@sulnorte.com.br' AND is_aux is null or login ='BrLo.STR';INSERT INTO TB_USUARIO ("ID_USUARIO", "ID_PERFIL", "ID_FILIAL", "NOME", "LOGIN", "SENHA", "SITUACAO", "IND_TP_USUARIO", "ID_TIPO", "ID_USUARIO_APROVADOR", "ID_USUARIO_PAR", "DS_EMAIL", "IN_APROVADOR", "IN_ATIVO", "DT_DESATIVACAO",is_aux) VALUES (sq_usuario.NEXTVAL, '2', '3', 'Bruno Loeser', 'BrLo.STR', 'b7a9681f61615b56e2d8f20afbf9dbedabd24df1', 'A', 'N', NULL, '1041', NULL, 'bruno.loeser@sulnorte.com.br', 'N', 'S', NULL,'A');
UPDATE TB_USUARIO set SITUACAO = 'I' where DS_EMAIL = 'alexandre.santos@sulnorte.com.br' AND is_aux is null or login ='AlSa.STR';INSERT INTO TB_USUARIO ("ID_USUARIO", "ID_PERFIL", "ID_FILIAL", "NOME", "LOGIN", "SENHA", "SITUACAO", "IND_TP_USUARIO", "ID_TIPO", "ID_USUARIO_APROVADOR", "ID_USUARIO_PAR", "DS_EMAIL", "IN_APROVADOR", "IN_ATIVO", "DT_DESATIVACAO",is_aux) VALUES (sq_usuario.NEXTVAL, '2', '3', 'Alexandre Santos', 'AlSa.STR', 'b7a9681f61615b56e2d8f20afbf9dbedabd24df1', 'A', 'N', NULL, '1041', NULL, 'alexandre.santos@sulnorte.com.br', 'N', 'S', NULL,'A');
UPDATE TB_USUARIO set SITUACAO = 'I' where DS_EMAIL = 'helton.farias@sulnorte.com.br' AND is_aux is null or login ='HeFa.STR';INSERT INTO TB_USUARIO ("ID_USUARIO", "ID_PERFIL", "ID_FILIAL", "NOME", "LOGIN", "SENHA", "SITUACAO", "IND_TP_USUARIO", "ID_TIPO", "ID_USUARIO_APROVADOR", "ID_USUARIO_PAR", "DS_EMAIL", "IN_APROVADOR", "IN_ATIVO", "DT_DESATIVACAO",is_aux) VALUES (sq_usuario.NEXTVAL, '2', '3', 'Helton Farias', 'HeFa.STR', 'b7a9681f61615b56e2d8f20afbf9dbedabd24df1', 'A', 'N', NULL, '1041', NULL, 'helton.farias@sulnorte.com.br', 'N', 'S', NULL,'A');
UPDATE TB_USUARIO set SITUACAO = 'I' where DS_EMAIL = 'alex.lode@sulnorte.com.br' AND is_aux is null or login ='AlLo.STR';INSERT INTO TB_USUARIO ("ID_USUARIO", "ID_PERFIL", "ID_FILIAL", "NOME", "LOGIN", "SENHA", "SITUACAO", "IND_TP_USUARIO", "ID_TIPO", "ID_USUARIO_APROVADOR", "ID_USUARIO_PAR", "DS_EMAIL", "IN_APROVADOR", "IN_ATIVO", "DT_DESATIVACAO",is_aux) VALUES (sq_usuario.NEXTVAL, '2', '3', 'Alex Lode', 'AlLo.STR', 'b7a9681f61615b56e2d8f20afbf9dbedabd24df1', 'A', 'N', NULL, '1041', NULL, 'alex.lode@sulnorte.com.br', 'N', 'S', NULL,'A');
UPDATE TB_USUARIO set SITUACAO = 'I' where DS_EMAIL = 'pedro.camargo@sulnorte.com.br' AND is_aux is null or login ='PeCa.STR';INSERT INTO TB_USUARIO ("ID_USUARIO", "ID_PERFIL", "ID_FILIAL", "NOME", "LOGIN", "SENHA", "SITUACAO", "IND_TP_USUARIO", "ID_TIPO", "ID_USUARIO_APROVADOR", "ID_USUARIO_PAR", "DS_EMAIL", "IN_APROVADOR", "IN_ATIVO", "DT_DESATIVACAO",is_aux) VALUES (sq_usuario.NEXTVAL, '2', '3', 'Pedro Camargo', 'PeCa.STR', 'b7a9681f61615b56e2d8f20afbf9dbedabd24df1', 'A', 'N', NULL, '1041', NULL, 'pedro.camargo@sulnorte.com.br', 'N', 'S', NULL,'A');
UPDATE TB_USUARIO set SITUACAO = 'I' where DS_EMAIL = 'carlos.medeiros@sulnorte.com.br' AND is_aux is null or login ='CaMe.STR';INSERT INTO TB_USUARIO ("ID_USUARIO", "ID_PERFIL", "ID_FILIAL", "NOME", "LOGIN", "SENHA", "SITUACAO", "IND_TP_USUARIO", "ID_TIPO", "ID_USUARIO_APROVADOR", "ID_USUARIO_PAR", "DS_EMAIL", "IN_APROVADOR", "IN_ATIVO", "DT_DESATIVACAO",is_aux) VALUES (sq_usuario.NEXTVAL, '2', '3', 'Carlos Medeiros', 'CaMe.STR', 'b7a9681f61615b56e2d8f20afbf9dbedabd24df1', 'A', 'N', NULL, '1041', NULL, 'carlos.medeiros@sulnorte.com.br', 'N', 'S', NULL,'A');
UPDATE TB_USUARIO set SITUACAO = 'I' where DS_EMAIL = 'danilo.sarraff@sulnorte.com.br' AND is_aux is null or login ='DaSa.STR';INSERT INTO TB_USUARIO ("ID_USUARIO", "ID_PERFIL", "ID_FILIAL", "NOME", "LOGIN", "SENHA", "SITUACAO", "IND_TP_USUARIO", "ID_TIPO", "ID_USUARIO_APROVADOR", "ID_USUARIO_PAR", "DS_EMAIL", "IN_APROVADOR", "IN_ATIVO", "DT_DESATIVACAO",is_aux) VALUES (sq_usuario.NEXTVAL, '2', '3', 'Danilo Sarraff', 'DaSa.STR', 'b7a9681f61615b56e2d8f20afbf9dbedabd24df1', 'A', 'N', NULL, '1041', NULL, 'danilo.sarraff@sulnorte.com.br', 'N', 'S', NULL,'A');
UPDATE TB_USUARIO set SITUACAO = 'I' where DS_EMAIL = 'leandro.medeiros@sulnorte.com.br' AND is_aux is null or login ='LeMe.STR';INSERT INTO TB_USUARIO ("ID_USUARIO", "ID_PERFIL", "ID_FILIAL", "NOME", "LOGIN", "SENHA", "SITUACAO", "IND_TP_USUARIO", "ID_TIPO", "ID_USUARIO_APROVADOR", "ID_USUARIO_PAR", "DS_EMAIL", "IN_APROVADOR", "IN_ATIVO", "DT_DESATIVACAO",is_aux) VALUES (sq_usuario.NEXTVAL, '2', '3', 'Leandro Medeiros', 'LeMe.STR', 'b7a9681f61615b56e2d8f20afbf9dbedabd24df1', 'A', 'N', NULL, '1041', NULL, 'leandro.medeiros@sulnorte.com.br', 'N', 'S', NULL,'A');
BrLo.STR: Bruno Loeser
AlSa.STR: Alexandre Santos
HeFa.STR: Helton Farias
AlLo.STR: Alex Lode
PeCa.STR: Pedro Camargo
CaMe.STR: Carlos Medeiros
DaSa.STR: Danilo Sarraff
LeMe.STR: Leandro Medeiros
