CREATE OR REPLACE 
PROCEDURE CARGA_SIG_TOP AS
BEGIN
	

DECLARE
	P_ID_OPERACAO NUMBER :=0;
	P_VLR_PTAX NUMBER := 0;
	P_ID_CONTRATO NUMBER := 0;
	P_NUM_CONTRATO VARCHAR(255);
	P_CD_TIPO_CONTRATO VARCHAR(255);
	P_DESC_TP_FATURAMENTO NUMBER;
	P_ID_EMPRESA VARCHAR(255) := 0;
	P_ID_DONO_DA_OP VARCHAR(255) := NULL;
	P_NOME_CLIENTE VARCHAR(255);
	P_ID_FILIAL NUMBER := 0;
	P_SIGLA_FILIAL VARCHAR(255);
	P_ID_ESTADO NUMBER := 0;
	P_ID_MUNICIPIO NUMBER := 0;
	P_SIGLA_ESTADO VARCHAR(255);
	P_ID_PORTO NUMBER := 0;
	P_DESCRICAO_PORTO VARCHAR(255) :='';
	P_ID_TERMINAL NUMBER := 0;
	P_DESCRICAO_TERMINAL VARCHAR(255) :='';
	P_ID_NAVIO NUMBER := 0;
	P_DWT_NAVIO NUMBER :=0;
	P_DESCRICAO_NAVIO VARCHAR(255);
	P_IMMO_NAVIO NUMBER := 0;
	P_ID_TEMPO DATE;
	P_ID_DONOREBOCADOR VARCHAR(255) :=0;
	COUNTER NUMBER := 0;
	W_COUNTER NUMBER 		:=	0;
	Y_TEMPO DATE;
	p_FATNF varchar(255);

	P_VLR_DESCONTO NUMBER;
	P_VLR_CC NUMBER;
	P_VLR_CAMBIO NUMBER;
	P_QTD_REBOCADORES_OPERACAO NUMBER;

	p_IND_AFRETAMENTO VARCHAR(1);
	P_LAST_IS_A_AFRETAMENTO BOOLEAN;
	P_LAST_IS_A_FATURAMENTO BOOLEAN;
	P_QTD_PROPRIOS_TOTAL_OPERACAO NUMBER;
	P_ID_CARGA NUMBER;
	P_DESCRICAO_CARGA VARCHAR(255);
	P_ID_AGENTE VARCHAR(255);
	P_DESCRICAO_AGENTE VARCHAR(255);
	P_ID_ARMADOR VARCHAR(255);
	P_DESCRICAO_ARMADOR VARCHAR(255);
	P_TIPO_FATURAMENTO VARCHAR(1);
	TYPE VECTOR IS TABLE OF VARCHAR (3) ; 
	ID_ANO_MKSHARE NUMBER;
	ID_MES_MKSHARE NUMBER;
	ID_DIA_MKSHARE NUMBER;
	MESES VECTOR := VECTOR (
		'Jan',
		'Fev',
		'Mar',
		'Abr',
		'Mai',
		'Jun',
		'Jul',
		'Ago',
		'Set',
		'Out',
		'Nov',
		'Dez'
	) ;

BEGIN
DBMS_OUTPUT.enable(10000000);
--remover
DELETE FROM "DW_sn_afretamento_fato" where SISTEMA_ORIGEM = 'TOP';
/*

*/
	delete from debug_terminais;
	DELETE FROM "DW_cliente";
	DELETE FROM "DW_contrato";
	DELETE FROM "DW_estado";
	DELETE FROM "DW_navio";
	DELETE FROM "DW_operacao";
	DELETE FROM "DW_porto";
	DELETE FROM "DW_rebocador";
	DELETE FROM "DW_rebocador";
	DELETE FROM "DW_sn_fato";
	DELETE FROM "DW_terminal";
	DELETE FROM "DW_carga";
	delete from "DW_nf";
	
	INSERT INTO "DW_nf"(FATNF) VALUES('INVOICE');
	INSERT INTO "DW_nf"(FATNF) VALUES('RECIBO NAO FATURADO');
	INSERT INTO "DW_nf"(FATNF) VALUES('RECIBO');
	insert into "DW_nf"(FATNF) values('FATURA NÃO INTEGRADA');
	FOR REG IN
	(
SELECT
	O.SITUACAO,O.ID_OPERACAO,O.FAT_DTSAIDA,O.IND_TP_TARIFA,O.ID_EMPRESA,CO.DT_CALCULO,O.ID_FILIAL,O.IND_OP_COMPARTILHADA,O.ID_DOM_TP_CARGA,O.ID_AGENTE,O.ID_ARMADOR,CO.VL_BRUTO_REAL,
CO.VL_CAMBIO,o.FAT_NF
FROM
	TB_OPERACAO O
	INNER JOIN TB_CALCULO_OPERACAO CO ON O.ID_OPERACAO = CO.ID_OPERACAO 
WHERE
--	O.ID_FILIAL = 3 AND
	(
		O.SITUACAO = 'F'
			OR
			O.SITUACAO = 'A'
	)AND 
		TO_CHAR(CO.DT_CALCULO,'YY') BETWEEN 11 AND 15
/*
[1.2]
SELECT
	CO.*,NVL(O.FAT_DTSAIDA,CO.DT_CALCULO) FAT_DTSAIDA,O.ID_FILIAL,O.IND_OP_COMPARTILHADA
FROM
	TB_OPERACAO O
	INNER JOIN TB_CALCULO_OPERACAO CO ON O.ID_OPERACAO = CO.ID_OPERACAO 
WHERE
	TO_CHAR(FAT_DTSAIDA,'YY') BETWEEN 11 AND 13
	AND
	O.SITUACAO = 'F'
	OR O.SITUACAO = 'A'*/
/*
	AND O.IND_OP_COMPARTILHADA = 4

	AND O.ID_OPERACAO IN (
		SELECT ID_OPERACAO FROM VW_OPERACAO_REBOCADOR WHERE ID_OPERACAO = O.ID_OPERACAO AND PROPRIO = 'S'
	)
*/
)
	LOOP

	ID_ANO_MKSHARE := null;
	ID_MES_MKSHARE :=null;
	ID_DIA_MKSHARE :=null;
	p_FATNF := null;
		--CARGA DW OPERACAO
			P_LAST_IS_A_AFRETAMENTO := FALSE;
			P_LAST_IS_A_FATURAMENTO := FALSE;
			SELECT COUNT(ID_OPERACAO) INTO P_QTD_PROPRIOS_TOTAL_OPERACAO FROM VW_OPERACAO_REBOCADOR  
			WHERE ID_OPERACAO = REG.ID_OPERACAO AND PROPRIO = 'S';
			BEGIN 
				SELECT DATA_FIM INTO Y_TEMPO FROM VW_OPERACAO_REBOCADOR WHERE ID_OPERACAO = REG.ID_OPERACAO AND ROWNUM =1;
			END;
			BEGIN
					SELECT ID_OPERACAO INTO P_ID_OPERACAO FROM "DW_operacao" WHERE ID_OPERACAO = REG.ID_OPERACAO;
			EXCEPTION
				WHEN NO_DATA_FOUND THEN
					INSERT INTO "DW_operacao"(ID_OPERACAO) VALUES(REG.ID_OPERACAO);
			END;
BEGIN
  P_ID_AGENTE := REG.ID_AGENTE;
--VALE
	if P_ID_AGENTE in('1146',
'1061',
'754',
'954',
'1103',
'210',
'13') THEN
			P_ID_AGENTE := 'VAL';
			P_DESCRICAO_AGENTE := 'VALE';
	-->SAVEIROS
	elsif P_ID_AGENTE IN('930','933','934','943','944','946','961','963','978') THEN
			P_ID_AGENTE := 'SAV';
			P_DESCRICAO_AGENTE := 'SAVEIROS';
	-->TUGBRASIL
	ELSIF P_ID_AGENTE IN('935','936','937','938','939','940','941') THEN
			P_ID_AGENTE := 'TUG';
			P_DESCRICAO_AGENTE := 'TUGBRASIL';
	-->SMIT
	ELSIF P_ID_AGENTE IN('969','973','975','1088','1113','1301') THEN
			P_ID_AGENTE := 'SMT';
			P_DESCRICAO_AGENTE := 'SMIT REBRAS';
	-->CAMORIM
	ELSIF P_ID_AGENTE IN('929','1014') THEN
			P_ID_AGENTE := 'CAM';
			P_DESCRICAO_AGENTE := 'CAMORIM';
	-->TRANSHIP
	ELSIF P_ID_AGENTE IN('697','928','832','258','283') THEN
			P_ID_AGENTE := 'TRN';
			P_DESCRICAO_AGENTE := 'TRANSHIP';
	-->SOBRAE
	ELSIF P_ID_AGENTE IN('953','960','960') THEN
			P_ID_AGENTE := 'SAV';
			P_DESCRICAO_AGENTE := 'SAVEIROS';
	--SULNORTE 
	ELSIF P_ID_AGENTE in('948','949','950','951','952','955','956','957','958') THEN
			P_ID_AGENTE := 'SN';
			P_DESCRICAO_AGENTE := 'SULNORTE';

	ELSIF P_ID_AGENTE in ('1033','746'	,'972'	,'1056'	,'1116'	,'218','223'	,'297'	,'228'	,'230'	,'263'	,'521'	,'5','6'	,'104'	,'439'	,'1442')
	THEN
			P_ID_AGENTE := 'PETR';
			P_DESCRICAO_AGENTE := 'PETROBRAS';
	END IF;
END;
BEGIN
--ID_DOM_TP_CARGA
SELECT ID_CLIENTE INTO P_ID_AGENTE FROM "DW_cliente" WHERE ID_CLIENTE = P_ID_AGENTE;
	EXCEPTION WHEN NO_DATA_FOUND THEN
		BEGIN
				IF P_DESCRICAO_AGENTE IS NULL THEN
				SELECT RAZAO_SOCIAL INTO P_DESCRICAO_AGENTE FROM TB_EMPRESA WHERE ID_EMPRESA = REG.ID_AGENTE;
				END IF;
		EXCEPTION
		WHEN NO_DATA_FOUND THEN
			DBMS_OUTPUT.PUT_LINE('AG:'||REG.ID_AGENTE || ' '|| REG.ID_OPERACAO);
		END;
		INSERT INTO "DW_cliente"(ID_CLIENTE,NOME_CLIENTE) VALUES(P_ID_AGENTE,CONVERT(P_DESCRICAO_AGENTE, 'WE8DEC', 'UTF8'));
END;


BEGIN
  P_ID_ARMADOR := REG.ID_ARMADOR;
	if P_ID_ARMADOR in('1146',
'1061',
'754',
'954',
'1103',
'210',
'13') THEN
			P_ID_ARMADOR := 'VAL';
			P_DESCRICAO_ARMADOR := 'VALE';
	-->SAVEIROS
	elsIF P_ID_ARMADOR IN('930','933','934','943','944','946','961','963','978') THEN
			P_ID_ARMADOR := 'SAV';
			P_DESCRICAO_ARMADOR := 'SAVEIROS';
	-->TUGBRASIL
	ELSIF P_ID_ARMADOR IN('935','936','937','938','939','940','941') THEN
			P_ID_ARMADOR := 'TUG';
			P_DESCRICAO_ARMADOR := 'TUGBRASIL';
	-->SMIT
	ELSIF P_ID_ARMADOR IN('969','973','975','1088','1113','1301') THEN
			P_ID_ARMADOR := 'SMT';
			P_DESCRICAO_ARMADOR := 'SMIT REBRAS';
	-->CAMORIM
	ELSIF P_ID_ARMADOR IN('929','1014') THEN
			P_ID_ARMADOR := 'CAM';
			P_DESCRICAO_ARMADOR := 'CAMORIM';
	-->TRANSHIP
	ELSIF P_ID_ARMADOR IN('697','928','832','258','283') THEN
			P_ID_ARMADOR := 'TRN';
			P_DESCRICAO_ARMADOR := 'TRANSHIP';
	-->SOBRAE
	ELSIF P_ID_ARMADOR IN('953','960','960') THEN
			P_ID_ARMADOR := 'SAV';
			P_DESCRICAO_ARMADOR := 'SAVEIROS';
	--SULNORTE 
	ELSIF P_ID_ARMADOR in('948','949','950','951','952','955','956','957','958') THEN
			P_ID_ARMADOR := 'SN';
			P_DESCRICAO_ARMADOR := 'SULNORTE';

	ELSIF P_ID_ARMADOR in ('1033','746'	,'972'	,'1056'	,'1116'	,'218','223'	,'297'	,'228'	,'230'	,'263'	,'521'	,'5','6'	,'104'	,'439'	,'1442')
	THEN
			P_ID_ARMADOR := 'PETR';
			P_DESCRICAO_ARMADOR := 'PETROBRAS';
	END IF;
END;
BEGIN
SELECT ID_CLIENTE INTO P_ID_ARMADOR FROM "DW_cliente" WHERE ID_CLIENTE = P_ID_ARMADOR;
	EXCEPTION WHEN NO_DATA_FOUND THEN
		BEGIN
			IF P_DESCRICAO_ARMADOR IS NULL THEN
				SELECT RAZAO_SOCIAL INTO P_DESCRICAO_ARMADOR FROM TB_EMPRESA WHERE ID_EMPRESA = REG.ID_ARMADOR;	
			END IF;
			INSERT INTO "DW_cliente"(ID_CLIENTE,NOME_CLIENTE) VALUES(P_ID_ARMADOR,CONVERT(P_DESCRICAO_ARMADOR, 'WE8DEC', 'UTF8'));
	EXCEPTION
		WHEN NO_DATA_FOUND THEN
			DBMS_OUTPUT.PUT_LINE('AR:'||REG.ID_AGENTE || ' ' || REG.ID_OPERACAO);
		END;
END;
BEGIN
SELECT ID_CARGA INTO P_ID_CARGA FROM "DW_carga" WHERE ID_CARGA = REG.ID_DOM_TP_CARGA;
	EXCEPTION WHEN NO_DATA_FOUND THEN
		SELECT DESCRICAO INTO P_DESCRICAO_CARGA FROM TB_DOMINIO WHERE ID_DOMINIO = REG.ID_DOM_TP_CARGA;
		INSERT INTO "DW_carga"(ID_CARGA,DESCRICAO_CARGA) VALUES(REG.ID_DOM_TP_CARGA,P_DESCRICAO_CARGA);
END;
			-- DBMS_OUTPUT.PUT_LINE(REG.ID_OPERACAO);
		-- 
		-- CONTRATO { -- SELECT * FROM VW_CONTRSATO

					BEGIN
					SELECT ID_CONTRATO INTO P_ID_CONTRATO FROM TB_OPERACAO WHERE ID_OPERACAO = REG.ID_OPERACAO;
					EXCEPTION WHEN NO_DATA_FOUND THEN
						DBMS_OUTPUT.PUT_LINE(REG.ID_OPERACAO || '	NÃO ENCONTRADO CONTRATO');
					END;

					BEGIN
						select FATNF into p_FATNF from "DW_nf" where FATNF = reg.FAT_NF||'';
						EXCEPTION WHEN NO_DATA_FOUND THEN
						if reg.FAT_NF is not null then
							insert into "DW_nf"(FATNF) values(reg.FAT_NF);
							p_FATNF := reg.FAT_NF;
						else
							if reg.SITUACAO = 'F' THEN
								p_FATNF :='FATURA NÃO INTEGRADA';
							ELSE
								p_FATNF := 'RECIBO NAO FATURADO';
							end if;
						end if;
					END;
BEGIN
	SELECT NUM_CONTRATO,CD_TIPO_CONTRATO,decode(DESC_TP_FATURAMENTO,'FATURA',1,'INVOICE',2) INTO P_NUM_CONTRATO,P_CD_TIPO_CONTRATO,P_DESC_TP_FATURAMENTO FROM VW_CONTRATO WHERE ID_CONTRATO = P_ID_CONTRATO;
	EXCEPTION WHEN NO_DATA_FOUND THEN
		DBMS_OUTPUT.PUT_LINE('NÃO ENCONTRADO CONTRATO:: '|| P_ID_CONTRATO||'	NUM_CONTRATO,CD_TIPO_CONTRATO,DESC_TP_FATURAMENTO');
END;
					BEGIN
						SELECT ID_CONTRATO INTO P_ID_CONTRATO FROM "DW_contrato" WHERE ID_CONTRATO = P_ID_CONTRATO;
						EXCEPTION
								WHEN NO_DATA_FOUND THEN
									INSERT INTO "DW_contrato"(ID_CONTRATO,NUM_CONTRATO,TIPO_CONTRATO) 
										VALUES(P_ID_CONTRATO,P_NUM_CONTRATO,P_CD_TIPO_CONTRATO);
					END;
	if p_FATNF = 'RECIBO NAO FATURADO' THEN
		P_DESC_TP_FATURAMENTO := 4;
	end if;
BEGIN
	P_ID_EMPRESA := REG.ID_EMPRESA;	
-- VALE
if P_ID_EMPRESA in('1146',
'1061',
'754',
'954',
'1103',
'210',
'13') THEN
			P_ID_EMPRESA := 'VAL';
			P_NOME_CLIENTE := 'VALE';
	-->SAVEIROS

	elsIF P_ID_EMPRESA IN('930','933','934','943','944','946','961','963','978') THEN
			P_ID_EMPRESA := 'SAV';
			P_NOME_CLIENTE := 'SAVEIROS';
	-->TUGBRASIL
	ELSIF P_ID_EMPRESA IN('935','936','937','938','939','940','941') THEN
			P_ID_EMPRESA := 'TUG';
			P_NOME_CLIENTE := 'TUGBRASIL';
	-->SMIT
	ELSIF P_ID_EMPRESA IN('969','973','975','1088','1113','1301') THEN
			P_ID_EMPRESA := 'SMT';
			P_NOME_CLIENTE := 'SMIT REBRAS';
	-->CAMORIM
	ELSIF P_ID_EMPRESA IN('929','1014') THEN
			P_ID_EMPRESA := 'CAM';
			P_NOME_CLIENTE := 'CAMORIM';
	-->TRANSHIP
	ELSIF P_ID_EMPRESA IN('697','928','832','258','283') THEN
			P_ID_EMPRESA := 'TRN';
			P_NOME_CLIENTE := 'TRANSHIP';
	-->SOBRAE
	ELSIF P_ID_EMPRESA IN('953','960','960') THEN
			P_ID_EMPRESA := 'SAV';
			P_NOME_CLIENTE := 'SAVEIROS';
	--SULNORTE 
	ELSIF P_ID_EMPRESA in('948','949','950','951','952','955','956','957','958') THEN
			P_ID_EMPRESA := 'SN';
			P_NOME_CLIENTE := 'SULNORTE';
	--PETROBRAS
	ELSIF P_ID_EMPRESA in ('1033','746','972','1056','1116','218','223','297','228','230','263','521','5','6','104','439','1442')
	THEN
			P_ID_EMPRESA := 'PETR';
			P_NOME_CLIENTE := 'PETROBRAS';
	END IF;
	

END;
					BEGIN
						SELECT ID_CLIENTE INTO P_ID_EMPRESA FROM "DW_cliente" WHERE ID_CLIENTE = P_ID_EMPRESA;
						EXCEPTION
							 WHEN NO_DATA_FOUND THEN
								IF P_NOME_CLIENTE IS NULL THEN
									SELECT RAZAO_SOCIAL INTO P_NOME_CLIENTE FROM TB_EMPRESA WHERE ID_EMPRESA = REG.ID_EMPRESA;
								END IF;
									INSERT INTO "DW_cliente"(ID_CLIENTE,NOME_CLIENTE) VALUES (P_ID_EMPRESA,CONVERT(P_NOME_CLIENTE, 'WE8DEC', 'UTF8'));
					END;


					
		-- }
		-- CARGA FILIAL{
	-------------------------------------------------------------

				BEGIN
						SELECT ID_FILIAL,SIGLA_FILIAL INTO P_ID_FILIAL,P_SIGLA_FILIAL 
						FROM "DW_filial" WHERE ID_FILIAL = REG.ID_FILIAL;
						P_ID_FILIAL := REG.ID_FILIAL;
					EXCEPTION 
						WHEN NO_DATA_FOUND THEN
						SELECT ID_FILIAL,SIGLA INTO P_ID_FILIAL,P_SIGLA_FILIAL FROM TB_FILIAL WHERE ID_FILIAL = REG.ID_FILIAL;
						INSERT INTO "DW_filial"(ID_FILIAL,SIGLA_FILIAL) VALUES(P_ID_FILIAL,P_SIGLA_FILIAL);
				END;
				BEGIN 
					SELECT ID_FILIAL,SIGLA_FILIAL INTO P_ID_FILIAL,P_SIGLA_FILIAL FROM "DW_filial" WHERE ID_FILIAL = REG.ID_FILIAL;
				EXCEPTION WHEN NO_DATA_FOUND THEN
					NULL;
				END;

				BEGIN
					SELECT ID_MUNICIPIO INTO P_ID_MUNICIPIO FROM TB_FILIAL WHERE ID_FILIAL = P_ID_FILIAL;
					SELECT ID_ESTADO INTO P_ID_ESTADO FROM TB_MUNICIPIO WHERE ID_MUNICIPIO = P_ID_MUNICIPIO;
					SELECT SIGLA INTO P_SIGLA_ESTADO FROM TB_ESTADO WHERE ID_ESTADO = P_ID_ESTADO AND ROWNUM =1;
					EXCEPTION WHEN NO_DATA_FOUND THEN
						NULL;
				END;

				BEGIN
						SELECT ID_ESTADO INTO P_ID_ESTADO FROM "DW_estado" WHERE ID_ESTADO = P_ID_ESTADO;
					EXCEPTION
						WHEN NO_DATA_FOUND THEN
							INSERT INTO "DW_estado"(ID_ESTADO,SIGLA) VALUES (P_ID_ESTADO,P_SIGLA_ESTADO);
				END;


-------------------------------------------------------------
				
		--}
			-- CARGA ESTADO{


		--}

		-- CARGA NAVIO -- SELECT * FROM TB_NAVIO WHERE ROWNUM = 1;
					SELECT ID_NAVIO INTO P_ID_NAVIO FROM TB_OPERACAO WHERE ID_OPERACAO = REG.ID_OPERACAO and rownum =1; 
					SELECT ID_NAVIO,DESCRICAO_NAVIO,DWT,IMO INTO P_ID_NAVIO,P_DESCRICAO_NAVIO,P_DWT_NAVIO,P_IMMO_NAVIO FROM TB_NAVIO WHERE ID_NAVIO = P_ID_NAVIO and rownum =1;
					BEGIN
						SELECT ID_NAVIO INTO P_ID_NAVIO FROM "DW_navio" WHERE ID_NAVIO = P_ID_NAVIO;
						EXCEPTION
							WHEN NO_DATA_FOUND THEN
								INSERT INTO "DW_navio"(ID_NAVIO,DWT,IMMO,NOME_NAVIO) VALUES (P_ID_NAVIO,P_DWT_NAVIO,P_IMMO_NAVIO,P_DESCRICAO_NAVIO);		
					END;

-- FATO
DECLARE 
		W_QTD_REB_TOTAL NUMBER;
		W_QTD_REB_AFRETADOS NUMBER;
		W_QTD_REB_PROPRIO NUMBER;
		W_VLR_LINER NUMBER;
		W_VLR_TRAMP NUMBER;
		W_VLR_TARIFA NUMBER;
		W_ID_REBOCADOR NUMBER;
		W_POTENCIA_REBOCADOR NUMBER;
		W_DESCRICAO_REBOCADOR VARCHAR(255);
		W_ID_TIPO_MANOBRA NUMBER;
		W_ANO_FABRICACAO_REBOCADOR NUMBER;
		W_CAMBIO NUMBER;
		W_ID_DONOREBOCADOR VARCHAR(255);
		N_ID_DONOREBOCADOR NUMBER;
		W_ID_INTERFATURAMENTO NUMBER := 0;
		W_MAX_DATA_FIM DATE;
		W_MIN_DATA_FIM DATE;
		D_ID_MANOBRA NUMBER;
		S_ID_TIPO_MANOBRA NUMBER;
		W_SIGLA_ESTADO VARCHAR(4);
		W_TEMP_PORTO_DESCR VARCHAR(255);
		S_ID_TERMINAL NUMBER;
		W_NOME_DONOREBOCADOR VARCHAR(255);
		S_ID_FILIAL VARCHAR(255);
		IS_AFRETAMENTO_CUSTO BOOLEAN := FALSE;
		IS_AFRETAMENTO_RECEITA BOOLEAN := FALSE;
		IS_OPERACAO_NORMAL BOOLEAN;
		W_TIPO_CALCULO VARCHAR(1);
		W_REG_DIVISOR NUMBER;
		V_VLR_AFRETAMENTO NUMBER;
		V_VLR_FATURAMENTO NUMBER;
		W_ID_MOTIVO NUMBER;
		W_DESCRICAO_MOTIVO VARCHAR(255);
		W_ID_CATEGORIA NUMBER;
		W_ID_MES NUMBER;
		W_ID_DIA_SEMANA NUMBER;
		W_ID_PERIODO_HORA NUMBER;
		W_ID_PERIODO_TURNO NUMBER;
		W_ID_MARKET_SHARE NUMBER;
		W_ID_ANO NUMBER;
		W_VLR_LINER_MARKET_SHARE NUMBER;
		W_VLR_TRAMP_MARKET_SHARE NUMBER;
		W_VLR_REAL_MARKET_SHARE NUMBER;
		W_VLR_DOLLAR_MARKET_SHARE NUMBER;
		W_JJ_DWT_ID NUMBER;
BEGIN
			FOR X IN (
SELECT
	THIS.*, CALCULO.VL_TOTAL_MANOBRA_REAL,
	CALCULO.VL_ISS_REAL
FROM
	VW_OPERACAO_REBOCADOR THIS
	LEFT OUTER JOIN 
		TB_CALCULO_MANOBRA CALCULO
		on THIS.ID_REBOCADOR = CALCULO.ID_REBOCADOR AND CALCULO.ID_MANOBRA_OPERACAO = THIS.ID_MANOBRA_OPERACAO
WHERE
	THIS.ID_OPERACAO = REG.ID_OPERACAO
ORDER BY
	ID_TIPO_MANOBRA,
	PROPRIO
/*
--unsable
		SELECT THIS.*,CALCULO.VL_TOTAL_MANOBRA_REAL,CALCULO.VL_ISS_REAL FROM VW_OPERACAO_REBOCADOR THIS,TB_CALCULO_MANOBRA CALCULO 
			WHERE THIS.ID_OPERACAO = REG.ID_OPERACAO 
			AND
				CALCULO.ID_MANOBRA_OPERACAO = THIS.ID_MANOBRA_OPERACAO
			AND 
				CALCULO.ID_REBOCADOR = THIS.ID_REBOCADOR 

ORDER BY ID_TIPO_MANOBRA,PROPRIO
*/
)
			LOOP


---- DECONTO -- BRANCH

--- NUMERO DE REBOCADORES EM TUDO -- TEST:102123

		SELECT COUNT(*) INTO P_QTD_REBOCADORES_OPERACAO 
				FROM VW_OPERACAO_REBOCADOR THIS
LEFT OUTER JOIN 
TB_CALCULO_MANOBRA CALCULO 
ON
				CALCULO.ID_MANOBRA_OPERACAO = THIS.ID_MANOBRA_OPERACAO AND 
				CALCULO.ID_REBOCADOR = THIS.ID_REBOCADOR
			WHERE THIS.ID_OPERACAO = REG.ID_OPERACAO ;
/*
		SELECT COUNT(*) INTO P_QTD_REBOCADORES_OPERACAO 
				FROM VW_OPERACAO_REBOCADOR THIS,TB_CALCULO_MANOBRA CALCULO 
			WHERE THIS.ID_OPERACAO = REG.ID_OPERACAO 
			AND
				CALCULO.ID_MANOBRA_OPERACAO = THIS.ID_MANOBRA_OPERACAO
			AND 
				CALCULO.ID_REBOCADOR = THIS.ID_REBOCADOR;
*/
			BEGIN
				SELECT sum(VL_CARTA_CREDITO)/P_QTD_REBOCADORES_OPERACAO INTO P_VLR_CC 
					FROM TB_CARTA_CREDITO
				WHERE ID_OPERACAO =REG.ID_OPERACAO and DS_SITUACAO = 'A';
				EXCEPTION WHEN NO_DATA_FOUND THEN
					NULL;
			END;

			select VL_DESCONTO_REAL/P_QTD_REBOCADORES_OPERACAO INTO P_VLR_DESCONTO 
				from TB_CALCULO_OPERACAO where ID_OPERACAO = REG.ID_OPERACAO;

			select VL_CAMBIO/P_QTD_REBOCADORES_OPERACAO INTO P_VLR_CAMBIO 
				from TB_CALCULO_OPERACAO where ID_OPERACAO = REG.ID_OPERACAO;
			
---/
				BEGIN
					SELECT ID_TIPO_MANOBRA INTO W_ID_TIPO_MANOBRA FROM "DW_tipo_manobra" WHERE ID_TIPO_MANOBRA = X.ID_TIPO_MANOBRA;
					EXCEPTION WHEN NO_DATA_FOUND THEN
						INSERT INTO "DW_tipo_manobra"(ID_TIPO_MANOBRA,NOME_TIPO_MANOBRA) VALUES(X.ID_TIPO_MANOBRA,X.DESCRICAO_MONOBRA);
						W_ID_TIPO_MANOBRA := X.ID_TIPO_MANOBRA;
				END;
		
				S_ID_FILIAL := P_ID_FILIAL;
				SELECT ID_DOM_MOTIVO_UTILZ INTO W_ID_MOTIVO FROM TB_REBOCADOR_MANOBRA WHERE ID_MANOBRA_OPERACAO = X.ID_MANOBRA_OPERACAO 
AND ID_REBOCADOR = x.id_REBOCADOR AND ROWNUM =1;
				BEGIN 
						SELECT ID_MOTIVO INTO W_ID_MOTIVO FROM "DW_motivo" WHERE ID_MOTIVO = W_ID_MOTIVO;
				EXCEPTION WHEN NO_DATA_FOUND THEN
						SELECT DESCRICAO INTO W_DESCRICAO_MOTIVO FROM TB_DOMINIO WHERE ID_DOMINIO = W_ID_MOTIVO;
						INSERT INTO "DW_motivo"(ID_MOTIVO,DESCRICAO_MOTIVO) VALUES(W_ID_MOTIVO,W_DESCRICAO_MOTIVO);
				END;
				IF X.ID_TIPO_MANOBRA IN(163	,161	,162	,164	,201	,7	,10	,12	,15	,16	,18	,20	,23	,25	,26	,33	,34	,37	,41	,
42	,
43	,
44	,
45	,
46	,
50	,
221	,
1	,
2	,
301	
) THEN
					W_ID_CATEGORIA := 2;
				 ELSE
					W_ID_CATEGORIA := 1;
				END IF;

				SELECT MAXIMA INTO W_MAX_DATA_FIM FROM (
								SELECT
										MAX(DATA_FIM) MAXIMA 
									FROM
										VW_OPERACAO_REBOCADOR
									WHERE
										ID_OPERACAO = REG.ID_OPERACAO

/*
									AND ID_TIPO_MANOBRA = X.ID_TIPO_MANOBRA
									AND ID_MANOBRA_OPERACAO = X.ID_MANOBRA_OPERACAO
*/

									/*AND
										(DATA_FIM - DATA_INICIO) < 60*/
									GROUP BY TO_CHAR(DATA_INICIO,'YY')
									ORDER BY COUNT(DATA_FIM) DESC
				) WHERE ROWNUM = 1;

ID_MES_MKSHARE := TO_CHAR(W_MAX_DATA_FIM,'MM');
				ID_DIA_MKSHARE := TO_CHAR(W_MAX_DATA_FIM,'DD');
				ID_ANO_MKSHARE := TO_CHAR(W_MAX_DATA_FIM,'YYYY');

		IF REG.SITUACAO = 'F' AND REG.FAT_DTSAIDA IS NOT NULL THEN
			W_MAX_DATA_FIM := REG.FAT_DTSAIDA;
		END IF;

				P_ID_TEMPO := W_MAX_DATA_FIM;

				W_ID_MES := TO_CHAR(W_MAX_DATA_FIM,'MM');
				W_ID_DIA_SEMANA := TO_CHAR(W_MAX_DATA_FIM,'D');
				W_ID_ANO := TO_CHAR(W_MAX_DATA_FIM,'YYYY');


BEGIN

	SELECT ID_TURNO 
			INTO W_ID_PERIODO_HORA FROM 
				"DW_TEMPO_periodo_hora" 
				WHERE TO_CHAR(TO_DATE(X.HORA_FIM,'HH24:MI'),'HH24') 
				BETWEEN HORA_INICIAL AND HORA_FINAL AND ROWNUM =1;

	SELECT ID_PERIODO 
			INTO W_ID_PERIODO_TURNO FROM 
				"DW_TEMPO_periodo_turno" 
				WHERE TO_CHAR(TO_DATE(X.HORA_FIM,'HH24:MI'),'HH24') 
				BETWEEN HORA_INICIAL AND HORA_FINAL AND ROWNUM=1;

EXCEPTION WHEN OTHERS
THEN
	NULL;
	--RAISE_APPLICATION_ERROR(-20000,REG.ID_OPERACAO || ' ' || X.DATA_FIM || ' '||TO_CHAR(X.HORA_FIM,'HH24'));
END;
				BEGIN
						SELECT PORTO.DESCRICAO INTO W_TEMP_PORTO_DESCR
							FROM TB_TERMINAL TER,
							TB_PORTO PORTO,
							TB_MUNICIPIO MUN
							WHERE 
							PORTO.ID_PORTO = TER.ID_PORTO AND
							MUN.ID_MUNICIPIO = PORTO.ID_MUNICIPIO
							AND
							ID_TERMINAL = X.ID_TERMINAL AND ROWNUM =1;
						
							IF W_TEMP_PORTO_DESCR = 'ITAJAI' THEN
									S_ID_FILIAL 		:= 4;
									P_ID_ESTADO 		:= 19;
									P_ID_MUNICIPIO 	:= 5;
							END IF;

							IF W_TEMP_PORTO_DESCR = 'TEMADRE' THEN
							BEGIN
									SELECT ID_FILIAL INTO S_ID_FILIAL FROM "DW_filial" WHERE SIGLA_FILIAL = 'TMD';
									EXCEPTION WHEN NO_DATA_FOUND THEN
										INSERT INTO "DW_filial"(ID_FILIAL,SIGLA_FILIAL) VALUES(999,'TMD');
										INSERT INTO "DW_filial"(ID_FILIAL,SIGLA_FILIAL) VALUES(997,'APM');
										INSERT INTO "DW_filial"(ID_FILIAL,SIGLA_FILIAL) VALUES(996,'GUA');
										S_ID_FILIAL := 999;
							END;
							END IF;
				END;
				SELECT COUNT(*) INTO W_QTD_REB_PROPRIO FROM VW_OPERACAO_REBOCADOR WHERE ID_OPERACAO = REG.ID_OPERACAO AND PROPRIO = 'S' AND ID_TIPO_MANOBRA = X.ID_TIPO_MANOBRA and id_manobra_operacao = x.id_manobra_operacao;
				
				SELECT
					COUNT (*) INTO W_QTD_REB_TOTAL
				FROM
					VW_OPERACAO_REBOCADOR
				WHERE
					ID_OPERACAO = REG.ID_OPERACAO
				AND ID_TIPO_MANOBRA = X.ID_TIPO_MANOBRA
				AND id_manobra_operacao = x.id_manobra_operacao ;

				SELECT
					COUNT (*) INTO W_QTD_REB_AFRETADOS
				FROM
					VW_OPERACAO_REBOCADOR
				WHERE
					ID_OPERACAO = REG.ID_OPERACAO
				AND PROPRIO = 'N'
				AND ID_TIPO_MANOBRA = X.ID_TIPO_MANOBRA
				AND id_manobra_operacao = x.id_manobra_operacao ; -- CARGA TERMINAL{


					SELECT ID_TERMINAL,DESCRICAO_TERMINAL INTO P_ID_TERMINAL,P_DESCRICAO_TERMINAL FROM VW_OPERACAO_REBOCADOR WHERE ID_MANOBRA_OPERACAO =	X.ID_MANOBRA_OPERACAO AND ROWNUM = 1;	
					BEGIN
						SELECT ID_TERMINAL INTO P_ID_TERMINAL FROM "DW_terminal" WHERE ID_TERMINAL = P_ID_TERMINAL;
						EXCEPTION WHEN NO_DATA_FOUND THEN
								INSERT INTO "DW_terminal" VALUES(P_ID_TERMINAL,P_DESCRICAO_TERMINAL);
					END;

				S_ID_TERMINAL := P_ID_TERMINAL;

				IF P_ID_TERMINAL = 195 THEN
					S_ID_TERMINAL := 10;
				END IF;
				IF P_ID_TERMINAL = 255 THEN
					S_ID_TERMINAL := 187;
				END IF;

				BEGIN
					SELECT ID_REBOCADOR INTO W_ID_REBOCADOR FROM "DW_rebocador" WHERE ID_REBOCADOR = X.ID_REBOCADOR;
					EXCEPTION WHEN NO_DATA_FOUND THEN
							INSERT INTO "DW_rebocador" (
								ID_REBOCADOR,
								NOME_REBOCADOR,
								ANO_FABRICACAO,
								POTENCIA,
								PROPRIO
							)
							VALUES
								(
									X.ID_REBOCADOR,
									X.DESCRICAO_REBOCADOR,
									X.ANO_FABRICACAO,
									X.POTENCIA,
									X.PROPRIO
								) ;
				END;
BEGIN

	SELECT ID_EMPRESA INTO W_ID_DONOREBOCADOR FROM TB_REBOCADOR WHERE ID_REBOCADOR = X.ID_REBOCADOR;
EXCEPTION WHEN NO_DATA_FOUND THEN
	DBMS_OUTPUT.PUT_LINE('SELECT ID_EMPRESA INTO W_ID_DONOREBOCADOR'||X.ID_REBOCADOR);
END;

IF REG.ID_OPERACAO = 74844 THEN

	DBMS_OUTPUT.PUT_LINE('TERMINAL:'||P_ID_TERMINAL||':W_ID_DONOREBOCADOR:'||W_ID_DONOREBOCADOR||':P_ID_FILIAL:'||P_ID_FILIAL||':P_DWT_NAVIO:'||P_DWT_NAVIO);

END IF;




		-- TEMPO			
				--SELECT MIN(DATA_FIM) INTO W_MIN_DATA_FIM FROM VW_OPERACAO_REBOCADOR WHERE ID_OPERACAO = REG.ID_OPERACAO;

/*

				BEGIN --
					-- [1.2] --> 
					SELECT TRUNC(DAY_ID) INTO P_ID_TEMPO FROM DW_TIME WHERE DAY_ID = TRUNC(W_MAX_DATA_FIM) AND ROWNUM = 1;
					--SELECT TRUNC(DAY_ID) INTO P_ID_TEMPO FROM DW_TIME WHERE DAY_ID = TRUNC(REG.DT_CALCULO) AND ROWNUM = 1;
				EXCEPTION
				 WHEN NO_DATA_FOUND THEN
					DBMS_OUTPUT.PUT_LINE('DNE.'||W_MAX_DATA_FIM);
				END;
*/
------SOMENTE AFRETAMENTO CUSTO
/*	

--DESCOMENTAR DEPOIS

IS_AFRETAMENTO_CUSTO 
		:= 	((REG.IND_OP_COMPARTILHADA = 1 AND W_QTD_REB_AFRETADOS > 0) OR -- AND X.PROPRIO = 'N'
				(REG.IND_OP_COMPARTILHADA = 3 AND W_QTD_REB_PROPRIO = 0));
*/
	/*IS_AFRETAMENTO_RECEITA
		:= ((REG.IND_OP_COMPARTILHADA = 4) AND W_QTD_REB_PROPRIO > 0); -- REG.IND_OP_COMPARTILHADA = 2 OR REG.IND_OP_COMPARTILHADA = 4
*/
	N_ID_DONOREBOCADOR := W_ID_DONOREBOCADOR;
IF IS_AFRETAMENTO_RECEITA THEN
	N_ID_DONOREBOCADOR := REG.ID_EMPRESA;
END IF;

BEGIN
		SELECT 
								ID_INTERFATURAMENTO,
								VLR_LINER,
								VLR_TRAMP
									INTO 
								W_ID_INTERFATURAMENTO,
								W_VLR_LINER,
								W_VLR_TRAMP
								FROM 
								(SELECT
									ID_INTERFATURAMENTO,
									VLR_LINER,
									VLR_TRAMP,decode(ID_CLIENTE,N_ID_DONOREBOCADOR,1,0) prioridade
								FROM
									TB_SIG_INTERFATURAMENTO
								WHERE
									(
										P_DWT_NAVIO BETWEEN DWT_INICIAL * 1000
										AND DWT_FINAL * 1000
									)
								AND(
									ID_CLIENTE = N_ID_DONOREBOCADOR
									OR ID_CLIENTE = -1
									OR ID_CLIENTE IS NOT NULL
								)
								--AND SIGLA_FILIAL = P_ID_FILIAL
								AND
								(
									(ID_TERMINAL = P_ID_TERMINAL OR (ID_TERMINAL = -1 AND SIGLA_FILIAL = P_ID_FILIAL) OR (ID_TERMINAL IS NOT NULL AND SIGLA_FILIAL = P_ID_FILIAL)) 
								)
								ORDER BY prioridade DESC) WHERE ROWNUM =1;

EXCEPTION when no_data_found THEN
	dbms_output.put_line('W_ID_DONOREBOCADOR'||W_ID_DONOREBOCADOR || ' '|| reg.ID_OPERACAO);
END;

SELECT ID_FAIXADWT INTO W_JJ_DWT_ID FROM "DW_faixaDWT" WHERE P_DWT_NAVIO BETWEEN INICIAL * 1000 AND FINAL * 1000
and ROWNUM =1;
BEGIN
							--OK!
	N_ID_DONOREBOCADOR :=	W_ID_DONOREBOCADOR;
if W_ID_DONOREBOCADOR in('1146',
'1061',
'754',
'954',
'1103',
'210',
'13') THEN
			W_ID_DONOREBOCADOR := 'VAL';
			W_NOME_DONOREBOCADOR := 'VALE';
	-->SAVEIROS

	elsIF W_ID_DONOREBOCADOR IN('930','933','934','943','944','946','961','963','978') THEN
			W_ID_DONOREBOCADOR := 'SAV';
			W_NOME_DONOREBOCADOR := 'SAVEIROS';
	-->TUGBRASIL
	ELSIF W_ID_DONOREBOCADOR IN('935','936','937','938','939','940','941') THEN
			W_ID_DONOREBOCADOR := 'TUG';
			W_NOME_DONOREBOCADOR := 'TUGBRASIL';
	-->SMIT
	ELSIF W_ID_DONOREBOCADOR IN('969','973','975','1088','1113','1301') THEN
			W_ID_DONOREBOCADOR := 'SMT';
			W_NOME_DONOREBOCADOR := 'SMIT REBRAS';
	-->CAMORIM
	ELSIF W_ID_DONOREBOCADOR IN('929','1014') THEN
			W_ID_DONOREBOCADOR := 'CAM';
			W_NOME_DONOREBOCADOR := 'CAMORIM';
	-->TRANSHIP
	ELSIF W_ID_DONOREBOCADOR IN('697','928','832','258','283') THEN
			W_ID_DONOREBOCADOR := 'TRN';
			W_NOME_DONOREBOCADOR := 'TRANSHIP';
	-->SOBRAE
	ELSIF W_ID_DONOREBOCADOR IN('953','960','953') THEN
			W_ID_DONOREBOCADOR := 'SAV';
			W_NOME_DONOREBOCADOR := 'SAVEIROS';
	--SULNORTE 
	ELSIF W_ID_DONOREBOCADOR in('948','949','950','951','952','955','956','957','958') THEN
			W_ID_DONOREBOCADOR := 'SN';
			W_NOME_DONOREBOCADOR := 'SULNORTE';
	ELSIF W_ID_DONOREBOCADOR in ('1033','746','972','1056','1116','218','223','297','228','230','263','521','5','6','104','439','1442')
	THEN
			W_ID_DONOREBOCADOR := 'PETR';
			W_NOME_DONOREBOCADOR := 'PETROBRAS';
	END IF;
END;

							BEGIN
								-- try
								SELECT ID_CLIENTE INTO W_ID_DONOREBOCADOR FROM "DW_cliente" WHERE ID_CLIENTE = W_ID_DONOREBOCADOR;
								EXCEPTION WHEN NO_DATA_FOUND THEN
									BEGIN
										IF W_NOME_DONOREBOCADOR IS NULL THEN
											SELECT RAZAO_SOCIAL INTO W_NOME_DONOREBOCADOR FROM TB_EMPRESA WHERE ID_EMPRESA = N_ID_DONOREBOCADOR;
										END IF;
										INSERT INTO "DW_cliente"(ID_CLIENTE,NOME_CLIENTE) VALUES(W_ID_DONOREBOCADOR,CONVERT(W_NOME_DONOREBOCADOR, 'WE8DEC', 'UTF8'));
									END;
							END;


					SELECT ID_PORTO INTO P_ID_PORTO FROM TB_TERMINAL WHERE ID_TERMINAL = P_ID_TERMINAL;
					SELECT DESCRICAO into P_DESCRICAO_PORTO from TB_PORTO where ID_PORTO = P_ID_PORTO;
					BEGIN
						SELECT ID_PORTO INTO P_ID_PORTO FROM "DW_porto" WHERE ID_PORTO = P_ID_PORTO;
						EXCEPTION
							WHEN NO_DATA_FOUND THEN
								INSERT INTO "DW_porto" VALUES(P_ID_PORTO,P_DESCRICAO_PORTO);
					END;
		--}
				-- CAMBIO
				BEGIN
								SELECT VL_CAMBIO INTO W_CAMBIO FROM "DW_cambio"
								WHERE 
--[1.2]-->>	TO_CHAR(DT_CAMBIO,'YY') = TO_CHAR(W_MIN_DATA_FIM,'YY')
								TO_CHAR(DT_CAMBIO,'YY') = TO_CHAR(P_ID_TEMPO,'YY')
								AND 
--[1.2]-->> TO_CHAR(DT_CAMBIO,'MM') = TO_CHAR(W_MIN_DATA_FIM,'MM');
								TO_CHAR(DT_CAMBIO,'MM') = TO_CHAR(P_ID_TEMPO,'MM');
				EXCEPTION WHEN NO_DATA_FOUND THEN
					DBMS_OUTPUT.PUT_LINE('CMBNE.'||P_SIGLA_FILIAL||' '||REG.ID_OPERACAO);
				END;
if W_CAMBIO is null or W_CAMBIO = 0 THEN
	W_CAMBIO := 2;
end if;
------------------------------------------------------ MARKET SHARE
BEGIN
SELECT
								ID_MARKET_SHARE,
								VLR_LINER,
								VLR_TRAMP INTO
								W_ID_MARKET_SHARE,
								W_VLR_LINER_MARKET_SHARE,
								W_VLR_TRAMP_MARKET_SHARE
							FROM
								TB_SIG_MARKET_SHARE
							WHERE
								( (P_DWT_NAVIO
									 BETWEEN DWT_INICIAL * 1000
									AND DWT_FINAL * 1000)
								)
							--AND SIGLA_FILIAL = P_ID_FILIAL
							AND(
								(ID_TERMINAL = P_ID_TERMINAL OR (ID_TERMINAL = -1 AND SIGLA_FILIAL = P_ID_FILIAL) OR (ID_TERMINAL IS NOT NULL AND SIGLA_FILIAL = P_ID_FILIAL)) 
							)
							AND(
								ID_MANOBRA = W_ID_TIPO_MANOBRA
								OR ID_MANOBRA = -1
								OR ID_MANOBRA IS NOT NULL
							) and rownum = 1
							ORDER BY
										DWT_FINAL DESC;




EXCEPTION WHEN NO_DATA_FOUND THEN
	--DBMS_OUTPUT.PUT_LINE('MSNE.'||P_DWT_NAVIO||' '||REG.ID_OPERACAO || ' t:'|| P_ID_TERMINAL);
			DECLARE 
				R NUMBER;
			BEGIN
				SELECT ID_TERMINAL INTO R FROM DEBUG_TERMINAIS WHERE ID_TERMINAL = P_ID_TERMINAL;
			EXCEPTION WHEN NO_DATA_FOUND THEN
				INSERT INTO DEBUG_TERMINAIS(ID_TERMINAL,DESCRICAO_TERMINAL,SIGLA_FILIAL,RAZAO,ID_MANOBRA,ID_OPERACAO) 
VALUES(P_ID_TERMINAL,P_DESCRICAO_TERMINAL,P_SIGLA_FILIAL,'MARKET SHARE',W_ID_TIPO_MANOBRA,REG.ID_OPERACAO);
			END;
END;
					IF REG.IND_TP_TARIFA = 'L' 
					THEN
						W_VLR_DOLLAR_MARKET_SHARE := W_VLR_LINER_MARKET_SHARE;
					ELSE
						W_VLR_DOLLAR_MARKET_SHARE := W_VLR_TRAMP_MARKET_SHARE;
					END IF;
						W_VLR_REAL_MARKET_SHARE 	:= W_VLR_DOLLAR_MARKET_SHARE*W_CAMBIO;
			IF NOT(P_SIGLA_FILIAL IN('ITA','SEP','VIT','MAC')) OR (P_SIGLA_FILIAL = 'MAC' AND REG.IND_TP_TARIFA = 'T') THEN
				W_VLR_DOLLAR_MARKET_SHARE := W_VLR_DOLLAR_MARKET_SHARE/W_QTD_REB_TOTAL;
				W_VLR_REAL_MARKET_SHARE 	:= W_VLR_DOLLAR_MARKET_SHARE*W_CAMBIO;
			END IF;

			IF P_SIGLA_FILIAL = 'MAC' AND REG.IND_TP_TARIFA = 'L' THEN
					W_VLR_REAL_MARKET_SHARE := W_VLR_DOLLAR_MARKET_SHARE;
					W_VLR_DOLLAR_MARKET_SHARE := W_VLR_DOLLAR_MARKET_SHARE/W_CAMBIO;
			END IF;



IF ((IS_AFRETAMENTO_CUSTO = FALSE and IS_AFRETAMENTO_RECEITA = FALSE)) THEN
		
		IS_OPERACAO_NORMAL := TRUE;

END IF; --fazer este para ambos false
/*
IF IS_AFRETAMENTO_RECEITA THEN
	W_ID_DONOREBOCADOR := 'SN';--P_ID_EMPRESA;
END IF;
*/
IF (IS_AFRETAMENTO_CUSTO AND X.PROPRIO = 'N'
) 
OR (IS_AFRETAMENTO_RECEITA AND X.PROPRIO = 'S'
) THEN

								-- RESGATAR VALOR AFRETADO
								-- SELECT * FROM TB_SIG_INTERFATURAMENTO WHERE ID_TERMINAL =-1
								BEGIN
									IF X.ID_TIPO_MANOBRA 
										-- especiais:
										IN(282,13,14,15,16,45,301,50,7,2,1,41,44,47,20,10,23,18,42,34,12,161,163,184,25,221,43,26,46,
										-- não especiais:
										27,30,29,8) THEN
										S_ID_TIPO_MANOBRA := 9;
									ELSE
										S_ID_TIPO_MANOBRA := X.ID_TIPO_MANOBRA;
									END IF;



-----------
/*
61	ATRACAÇÃO COM PASSAGEM DE PONTE
8	ATRACAÇÃO
11	MUDANÇA DE ATRACAÇÃO
21	MUDANÇA
35	ATRACAÇÃO STAND BY
3	ATRACAÇÃO COM 1 REBOCADOR
241	MUDANÇA COM 1 REBOCADOR

Desatracação = Atracação
Mudança = Atração com 25% de desconto
Atracação com 1  rebocador = Atracação com 45% de desconto
Mudança com 1 rebocador = Mudança com 45% de desconto
Atracação Stand by = Atracação com 50% de desconto

*/
					DECLARE 
						V_MUDANCA NUMBER;
					BEGIN
						V_MUDANCA := V_VLR_AFRETAMENTO - ((V_VLR_AFRETAMENTO*25)/100);

						IF X.ID_TIPO_MANOBRA  IN(11,21,81,82,22) THEN
								V_VLR_AFRETAMENTO := V_MUDANCA;
						ELSIF X.ID_TIPO_MANOBRA  IN(3,4,241) THEN 
								V_VLR_AFRETAMENTO := V_VLR_AFRETAMENTO - ((V_VLR_AFRETAMENTO*45)/100);
						ELSIF X.ID_TIPO_MANOBRA  IN(35,36) THEN 
								V_VLR_AFRETAMENTO := V_VLR_AFRETAMENTO/2;
						ELSIF X.ID_TIPO_MANOBRA  IN(61,62) THEN 
								V_VLR_AFRETAMENTO := V_VLR_AFRETAMENTO + ((V_VLR_AFRETAMENTO*25)/100);
						END IF;
					END;
								V_VLR_AFRETAMENTO := V_VLR_AFRETAMENTO * W_CAMBIO;

								EXCEPTION WHEN NO_DATA_FOUND THEN
										DECLARE 
											R NUMBER;
										BEGIN
											SELECT ID_TERMINAL INTO R FROM DEBUG_TERMINAIS WHERE ID_TERMINAL = P_ID_TERMINAL;
										EXCEPTION WHEN NO_DATA_FOUND THEN
											INSERT INTO DEBUG_TERMINAIS(ID_TERMINAL,DESCRICAO_TERMINAL,SIGLA_FILIAL,RAZAO,ID_MANOBRA,ID_OPERACAO) 
VALUES(P_ID_TERMINAL,P_DESCRICAO_TERMINAL,P_SIGLA_FILIAL,'AFRETAMENTO',W_ID_TIPO_MANOBRA,REG.ID_OPERACAO);
										END;
								END;

							DECLARE R EXCEPTION;
							BEGIN
									IF REG.IND_TP_TARIFA = 'L' THEN
											W_VLR_TARIFA := W_VLR_LINER;
									ELSIF REG.IND_TP_TARIFA = 'T' THEN
											W_VLR_TARIFA := W_VLR_TRAMP;
									ELSE
										RAISE R;
									END IF;
							END;

								IF P_SIGLA_FILIAL = 'ITA' THEN
										IF TO_CHAR(P_ID_TEMPO,'YY') = 12 THEN
											W_VLR_TARIFA := 2700;
										END IF;
										IF TO_CHAR(P_ID_TEMPO,'YY') = 13 THEN
											W_VLR_TARIFA := 1300;
										END IF;

										W_VLR_TARIFA := W_VLR_TARIFA * W_CAMBIO;

								END IF;

								DECLARE 
									NO_FILIAL_FOUND EXCEPTION;
								BEGIN
										IF IS_AFRETAMENTO_CUSTO THEN
											W_REG_DIVISOR := W_QTD_REB_AFRETADOS;
										ELSIF IS_AFRETAMENTO_RECEITA THEN
											W_REG_DIVISOR := W_QTD_REB_PROPRIO;
										END IF;
										IF P_SIGLA_FILIAL IN('PNG','STR','VIT','SDR','RGD') OR (P_SIGLA_FILIAL IN ('RJ1','RJ') AND /*tugBRASIL*/N_ID_DONOREBOCADOR IN('935','936','937','938','939','940','941')) THEN

											IF (P_SIGLA_FILIAL = 'VIT' AND W_ID_DONOREBOCADOR = '975') OR P_SIGLA_FILIAL <> 'VIT' THEN
--->>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
												W_VLR_TARIFA :=	((W_VLR_TARIFA/W_QTD_REB_TOTAL)*W_REG_DIVISOR) * W_CAMBIO;	

											END IF;

										ELSIF (P_SIGLA_FILIAL IN ('SEP','RJ','RJ1','VIT')) OR (P_SIGLA_FILIAL = 'MAC' AND REG.IND_TP_TARIFA = 'T' ) THEN
--->>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
											W_VLR_TARIFA :=	(W_VLR_TARIFA * W_REG_DIVISOR) * W_CAMBIO;

										ELSIF (P_SIGLA_FILIAL = 'MAC' AND REG.IND_TP_TARIFA = 'L' ) THEN
											
											W_VLR_TARIFA := W_VLR_TARIFA;

										END IF;
								END;

								IF X.ID_TIPO_MANOBRA IN(13,14,282) THEN
											W_VLR_TARIFA := W_VLR_TARIFA/2;
								END IF;
ELSE
	W_VLR_TARIFA :=0;
	W_ID_INTERFATURAMENTO :=-1;
END IF;
									-- INSERE VALOR

				IF IS_AFRETAMENTO_CUSTO THEN
					IF W_QTD_REB_AFRETADOS >0 THEN
						W_VLR_TARIFA := W_VLR_TARIFA/W_QTD_REB_AFRETADOS;
					END IF;
					W_TIPO_CALCULO := 'C';
					P_LAST_IS_A_AFRETAMENTO := TRUE;
					P_LAST_IS_A_FATURAMENTO := TRUE;
				END IF;
				IF IS_AFRETAMENTO_RECEITA THEN
					IF W_QTD_REB_PROPRIO >0 THEN
						W_VLR_TARIFA := W_VLR_TARIFA/W_QTD_REB_PROPRIO;
					END IF;
					W_TIPO_CALCULO := 'R';
					P_LAST_IS_A_AFRETAMENTO := TRUE;
				END IF;

				DECLARE
					NO_BUS_EXCEPTION EXCEPTION;
				BEGIN
					IF IS_OPERACAO_NORMAL THEN
						V_VLR_AFRETAMENTO := NULL;
						V_VLR_FATURAMENTO := X.VL_TOTAL_MANOBRA_REAL + X.VL_ISS_REAL;
					ELSIF(IS_AFRETAMENTO_CUSTO) THEN
						IF W_VLR_TARIFA = 0 THEN
							V_VLR_AFRETAMENTO := NULL;
						ELSE
							V_VLR_AFRETAMENTO := W_VLR_TARIFA;
						END IF;
						V_VLR_FATURAMENTO := X.VL_TOTAL_MANOBRA_REAL + X.VL_ISS_REAL;
					ELSIF IS_AFRETAMENTO_RECEITA THEN
						V_VLR_AFRETAMENTO := NULL;
						V_VLR_FATURAMENTO := W_VLR_TARIFA;
					ELSE
						RAISE NO_BUS_EXCEPTION;
					END IF;
/*
	Ac
	{
		Pr = TB_OPERACAO.IND_OP_COMPARTILHADA = 1 && { Ra > 0 
		||
		Cm = TB_OPERACAO.IND_OP_COMPARTILHADA = 3 && { Rp = 0
	}

	Ar
	{
		Ter = TB_OPERACAO.IND_OP_COMPARTILHADA = 2
		||
		Est = TB_OPERACAO.IND_OP_COMPARTILHADA = 4
		&&
		Rp > 0
	}--
(((REG.IND_OP_COMPARTILHADA in (2,4) ) AND W_QTD_REB_PROPRIO = 0)
							OR ((REG.IND_OP_COMPARTILHADA = 1 AND W_QTD_REB_AFRETADOS = 0) OR REG.IND_OP_COMPARTILHADA = 3 AND W_QTD_REB_PROPRIO > 0)) 
*/

				IF IS_OPERACAO_NORMAL THEN
					W_TIPO_CALCULO := 'F';
					IF X.IND_AFRETAMENTO = 'N' AND ((P_LAST_IS_A_AFRETAMENTO AND (NOT P_LAST_IS_A_FATURAMENTO)) OR P_QTD_PROPRIOS_TOTAL_OPERACAO = 0) THEN
							W_TIPO_CALCULO := 'S';
							P_LAST_IS_A_AFRETAMENTO := TRUE;
							W_ID_INTERFATURAMENTO := -1;
							V_VLR_AFRETAMENTO := NULL;
							V_VLR_FATURAMENTO := NULL;
					END IF;
				END IF;
				IF W_TIPO_CALCULO = 'F' THEN
					P_LAST_IS_A_AFRETAMENTO := FALSE;
					P_LAST_IS_A_FATURAMENTO := TRUE;
					W_ID_INTERFATURAMENTO := -1;
				END IF;
  IF W_QTD_REB_PROPRIO = 0 AND REG.IND_OP_COMPARTILHADA = 4 THEN
		W_TIPO_CALCULO := 'S';
	END IF;
	if x.proprio = 'S' AND REG.IND_OP_COMPARTILHADA = 2 THEN
		W_TIPO_CALCULO := 'R';
	end if;
/*
	IF X.PROPRIO = 'N' AND W_TEMP_PORTO_DESCR = 'TEMADRE' AND reg.VL_BRUTO_REAL > 450000 AND P_DESCRICAO_NAVIO = 'DIVERSOS NAVIOS' THEN
		V_VLR_AFRETAMENTO := (REG.VL_BRUTO_REAL/2)/W_QTD_REB_AFRETADOS;
	END IF;
*/
/*
	if REG.IND_OP_COMPARTILHADA in(2,4) THEN
		P_ID_DONO_DA_OP := 'SN';
	elsif reg.IND_OP_COMPARTILHADA in(1,3) THEN
		P_ID_DONO_DA_OP := P_ID_EMPRESA;
	end if;
*/

begin
select ide into P_ID_DONO_DA_OP from (

	SELECT
		(REB.ID_EMPRESA ||'') ide,count(*) 
	FROM
		VW_OPERACAO_REBOCADOR THIS	
		INNER JOIN 
			TB_OPERACAO O
				ON O.ID_OPERACAO = THIS.ID_OPERACAO
		LEFT OUTER JOIN 
			TB_CALCULO_MANOBRA CALCULO
			on THIS.ID_REBOCADOR = CALCULO.ID_REBOCADOR AND CALCULO.ID_MANOBRA_OPERACAO = THIS.ID_MANOBRA_OPERACAO
		INNER JOIN 
			TB_REBOCADOR REB
			ON REB.ID_REBOCADOR = THIS.ID_REBOCADOR
	WHERE
		THIS.ID_OPERACAO = REG.ID_OPERACAO
		AND ((THIS.IND_AFRETAMENTO = 'N' AND O.IND_OP_COMPARTILHADA <> 4) 
					OR (THIS.IND_AFRETAMENTO = 'S' and O.IND_OP_COMPARTILHADA = 4))
GROUP BY 
	THIS.ID_OPERACAO,REB.ID_EMPRESA
 )
where rownum =1
;
	EXCEPTION when no_data_found then
		P_ID_DONO_DA_OP := P_ID_EMPRESA;
end;

IF reg.IND_OP_COMPARTILHADA =1 THEN
	P_ID_DONO_DA_OP := 'SN';
END IF;
if P_ID_DONO_DA_OP in('1146',
'1061',
'754',
'954',
'1103',
'210',
'13') THEN
			P_ID_DONO_DA_OP := 'VAL';

elsIF P_ID_DONO_DA_OP IN('930','933','934','943','944','946','961','963','978') THEN
			P_ID_DONO_DA_OP := 'SAV';
	-->TUGBRASIL
	ELSIF P_ID_DONO_DA_OP IN('935','936','937','938','939','940','941') THEN
			P_ID_DONO_DA_OP := 'TUG';
	-->SMIT
	ELSIF P_ID_DONO_DA_OP IN('969','973','975','1088','1113','1301') THEN
			P_ID_DONO_DA_OP := 'SMT';
	-->CAMORIM
	ELSIF P_ID_DONO_DA_OP IN('929','1014') THEN
			P_ID_DONO_DA_OP := 'CAM';
	-->TRANSHIP
	ELSIF P_ID_DONO_DA_OP IN('697','928','832','258','283') THEN
			P_ID_DONO_DA_OP := 'TRN';
	-->SOBRAE
	ELSIF P_ID_DONO_DA_OP IN('953','960','960') THEN
			P_ID_DONO_DA_OP := 'SAV';
	--SULNORTE 
	ELSIF P_ID_DONO_DA_OP in('948','949','950','951','952','955','956','957','958') THEN
			P_ID_DONO_DA_OP := 'SN';

	ELSIF P_ID_DONO_DA_OP in ('1033','746'	,'972'	,'1056'	,'1116'	,'218','223'	,'297'	,'228'	,'230'	,'263'	,'521'	,'5','6'	,'104'	,'439'	,'1442')
	THEN
			P_ID_DONO_DA_OP := 'PETR';
	END IF;


p_IND_AFRETAMENTO := X.IND_AFRETAMENTO;

if W_ID_DONOREBOCADOR = P_ID_DONO_DA_OP THEN
	p_IND_AFRETAMENTO := 'N';
end if;
--PTAX
BEGIN

SELECT sum(MDN_VALOR)/2 into P_VLR_PTAX
FROM MOEDIN_MDN, MOEDA_MOE
WHERE MOE_CODIGO = MDN_CODIGO
AND MDN_CODIGO in ('DCC','DCV')
AND MDN_DATA = 
to_date(ID_DIA_MKSHARE||'/'|| ID_MES_MKSHARE ||'/'||ID_ANO_MKSHARE,'dd/mm/yyyy');


end;
--end PTAX





INSERT INTO "DW_sn_afretamento_fato" (
	ID_FATO,
	ID_TERMINAL,
	ID_PORTO,
	ID_DONOREBOCADOR,
	ID_REBOCADOR,
	VALOR_AFRETAMENTO,
	VALOR_MANOBRA,
	ID_TEMPO,
	ID_NAVIO,
	ID_TIPO_MANOBRA,
	ID_TIPO_TARIFACAO,
	ID_FILIAL,
	ID_INTERFATURAMENTO,
	ID_EMPRESA,
	ID_OPERACAO,
	ID_TIPO_CALCULO,
	ID_MOTIVO_MANOBRA,
	ID_CATEGORIA_MANOBRA,
	VALOR_FATURAMENTO_LIQUIDO,
	ID_CARGA,
	ID_ARMADOR,
	ID_AGENTE,
	ID_MES,
	ID_PERIODO_HORA,
	ID_PERIODO_TURNO,
	ID_SEMANA,
	VLR_REFERENCIA_DOLLAR,
	VLR_REFERENCIA_REAL,
	ID_ANO,
	ID_MARKET_SHARE,
	ID_ANOMES,
	ID_TARIFACAO,
	ID_DIA_MES,
	ID_FAIXADWT,
	ID_CONTRATO,
	FATURADO_DOLLAR,
	ID_FATNF,
	SISTEMA_ORIGEM,

	VLR_CAMBIO,
	VLR_CC,
	VLR_DESCONTO,
	VLR_DWT,ID_ANO_MKSHARE,
ID_MES_MKSHARE,
ID_DIA_MKSHARE,
ID_DONOOPERACAO,
ID_IND_AFRETAMENTO,vlr_ptax,
ID_DIA_MANOBRA,ID_MES_MANOBRA,ID_ANO_MANOBRA

	
)
VALUES
	(
		(W_COUNTER),
		P_ID_TERMINAL,
		P_ID_PORTO,
		W_ID_DONOREBOCADOR,
		X.ID_REBOCADOR,
		V_VLR_AFRETAMENTO,
		V_VLR_FATURAMENTO,
		P_ID_TEMPO,
		P_ID_NAVIO,
		X.ID_TIPO_MANOBRA,
		DECODE (
			REG.IND_TP_TARIFA,
			'L',
			1,
			'T',
			2
		),
		S_ID_FILIAL,
		W_ID_INTERFATURAMENTO,
		P_ID_EMPRESA,
		REG.ID_OPERACAO,
		W_TIPO_CALCULO,
		W_ID_MOTIVO,
		W_ID_CATEGORIA,
		V_VLR_FATURAMENTO - V_VLR_AFRETAMENTO,
		REG.ID_DOM_TP_CARGA,
		P_ID_ARMADOR,
		P_ID_AGENTE,
		W_ID_MES,
		W_ID_PERIODO_HORA,
		W_ID_PERIODO_TURNO,
		W_ID_DIA_SEMANA,
		W_VLR_DOLLAR_MARKET_SHARE,
		W_VLR_REAL_MARKET_SHARE,
		W_ID_ANO,
		W_ID_MARKET_SHARE,
		TO_CHAR (W_MAX_DATA_FIM, 'YYYY') || '/' || MESES (
			(
				TO_CHAR (W_MAX_DATA_FIM, 'MM')
			)
		),
		P_desc_tp_faturamento,
		TO_CHAR (W_MAX_DATA_FIM, 'DD'),
		W_JJ_DWT_ID,
		P_ID_CONTRATO,
		V_VLR_FATURAMENTO / REG.VL_CAMBIO,
		p_FATNF,
		'TOP',

		P_VLR_CAMBIO,
		P_VLR_CC,
		P_VLR_DESCONTO,
		(P_DWT_NAVIO),ID_ANO_MKSHARE,ID_MES_MKSHARE,ID_DIA_MKSHARE,
		P_ID_DONO_DA_OP,p_IND_AFRETAMENTO,P_VLR_PTAX,
		TO_CHAR(X.DATA_INICIO,'DD'),
		TO_CHAR(X.DATA_INICIO,'MM'),
		TO_CHAR(X.DATA_INICIO,'YYYY')

	) ;


					END;

	P_DESCRICAO_AGENTE := NULL;
	P_DESCRICAO_ARMADOR := NULL;
	P_NOME_CLIENTE := NULL;
	W_NOME_DONOREBOCADOR := NULL;

					W_COUNTER := W_COUNTER +1;
					END LOOP;--select * from "DW_sn_afretamento_fato"
			END;


	p_FATNF := NULL;
	COUNTER := COUNTER +1;
	END LOOP;
CARGA_SIG_RECIBO;
CARGA_SIG_COMBUSTIVEL;
-- delete from "DW_sn_afretamento_fato" where id_fato >= 312343234123
-- 
--delete from "DW_sn_afretamento_fato" where id_fato >= 1* 99090909099090;
------------				***************************************************************    FULL_TABLE
/*
BEGIN
delete from FULL_TABLE;
DECLARE
	MES NUMBER;
BEGIN
	FOR ANO IN 2013..2014
		LOOP
			FOR I IN 1..12 LOOP
				FOR X IN (SELECT ID_CONTA_CONTABIL FROM "DW_contacontabil")
				LOOP
						FOR F IN(SELECT SIGLA_FILIAL FROM "DW_filial")
						LOOP
							INSERT INTO FULL_TABLE(FILIAL_ALOCACAO,MES,VLR_REALIZADO,ID_CONTA_CONTABIL,ANO)
							VALUES(F.SIGLA_FILIAL,I,0,X.ID_CONTA_CONTABIL,ANO);
						END LOOP;
				END LOOP;
		END LOOP ;
	END LOOP;
END ;
---------------
BEGIN
	for JJ_K in (select ANO,FILIAL_ALOCACAO,MES,DIA,REALIZADO,ID_CONTA_CONTABIL,COD_CENTRO_CUSTO from PRD_JJ_CARGA)
	loop
		INSERT INTO FULL_TABLE(FILIAL_ALOCACAO,MES,VLR_REALIZADO,ID_CONTA_CONTABIL,ANO,DIA,CENTRODECUSTO)
		values(JJ_K.FILIAL_ALOCACAO,JJ_K.MES,JJ_K.REALIZADO,JJ_K.ID_CONTA_CONTABIL,JJ_K.ANO,JJ_K.DIA,JJ_K.COD_CENTRO_CUSTO);
	end loop;
end;
End;
-------
DECLARE
	J_ID_GRUPO NUMBER := 0;
	J_ID_FILIAL NUMBER;
	COUNTER number := 1;
BEGIN
	insert into "DW_filial"(ID_FILIAL,SIGLA_FILIAL) values(907,'MTZ');
	FOR J IN
	(
SELECT
	"ANO",
	"MES",
	"ID_ULTRAGRUPO",
	"NOME_ULTRAGRUPO",
	"ID_SUPERGROUPO",
	"NOME_SUPERGRUPO",
	"ID_GRUPOMASTER",
	"NAME_GRUPOMASTER",
	"ID_GRUPO",
	"NOME_GRUPO",
	"FILIAL_ALOCACAO",
	"ID_CONTA_CONTABIL",
	"NOME_CONTA_CONTABIL",
	"PREV",
	"REALIZADO","ORCADO2014"
from DEBUG_STABLE_GRUPOMASTER---DEBUG_STABLE_WPISCCONFIS--DEBUG_STABLE_WPISCCONFIS DEBUG_STABLE_GRUPOMASTER--PRD_JJ_CARGA
	)
	LOOP
/*
BEGIN
		COUNTER := COUNTER * 99090909099090;
	SELECT
		ID_GRUPO INTO J_ID_GRUPO
	FROM
		TB_PRD_GRUPO_CONTA GC,
		TB_PRD_GRUPO G
	WHERE
		GC.ID_GRUPO_CONTAS = G .ID_GRUPO
	AND TIPO_GRUPO <> 'P' AND ID_CONTA = J.ID_CONTA_CONTABIL AND ROWNUM = 1;
EXCEPTION WHEN NO_DATA_FOUND THEN
	J_ID_GRUPO := 60;
END;
*/
/*
IF J.ID_CONTA_CONTABIL = 310201009000000 THEN
J_ID_GRUPO := -1;
ELSIF J.ID_CONTA_CONTABIL like '3%' THEN
J_ID_GRUPO := 0;
END IF;

begin
	SELECT ID_FILIAL INTO J_ID_FILIAL FROM "DW_filial" WHERE SIGLA_FILIAL = J.FILIAL_ALOCACAO;
EXCEPTION when no_data_found THEN
null;
end;
DECLARE R NUMBER := 0;
BEGIN 
	R := J.PREV *-1;
*/
/*
	IF J.ID_CONTA_CONTABIL <> 310201009000000 THEN
			R := J.PREV *-1;
	ELSE
			R := J.PREV;
	END IF;
*/
/*
	INSERT INTO "DW_sn_afretamento_fato" (
		ID_FATO,
		ID_CONTACONTABIL,
		ID_FILIAL,
		ID_ANO,
		ID_MES,
		ID_GRUPOCONTA,
		VLR_ORCADO,
		VLR_REALIZADO,
		VLR_DIFERENCA_ORCADO_REALIZADO,ID_GRUPOMASTER,ID_SUPERGRUPO,ID_ULTRAGRUPO,VLR_ORCADONOVO)
	VALUES
	(COUNTER,J.ID_CONTA_CONTABIL,J_ID_FILIAL,J.ANO,J.MES,j.id_grupo,R,J.REALIZADO *-1,J.PREV - j.REALIZADO,j.ID_GRUPOMASTER,j.ID_SUPERGROUPO,j.ID_ULTRAGRUPO,j.orcado2014);
END;
	END LOOP;

END; 

*/

END;


END;
